name = "telegram-bot-panel"
compatibility_date = "2026-08-15"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

# Pengaturan Assets untuk file statis (HonoX)
[site]
bucket = "./public"

# Binding Database D1
[[d1_databases]]
binding = "DB"
database_name = "botpanel"
database_id = "6160bfaa-7b2a-4451-afc5-b5d9b8befdbf"
